# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Build matrix options
matrix:
  include:
#    - php: 5.5
#      env: GB_TRAVISCI=travis:js
    - php: 5.3
      env: GB_TRAVISCI=travis:phpunit
    - php: 5.4
      env: GB_TRAVISCI=travis:phpunit
    - php: 5.5
      env: GB_TRAVISCI=travis:phpunit
    - php: 5.6
      env: GB_TRAVISCI=travis:phpunit
    - php: hhvm
      env: GB_TRAVISCI=travis:phpunit
    - php: 7
      env: GB_TRAVISCI=travis:phpunit
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: 7
  fast_finish: true

# Before install, failures in this section will result in build status 'errored'
before_install:
  - GB_CORE_DIR=/tmp/genibase/
  - >
    if [[ "$GB_TRAVISCI" == "travis:phpunit" ]]; then
       mysql -e "CREATE DATABASE genibase_tests;" -uroot
       cp gb-tests-config-sample.php gb-tests-config.php
       sed -i "s/youremptytestdbnamehere/genibase_tests/" gb-tests-config.php
       sed -i "s/yourusernamehere/travis/" gb-tests-config.php
       sed -i "s/yourpasswordhere//" gb-tests-config.php
    fi
#        svn checkout https://plugins.svn.wordpress.org/wordpress-importer/trunk tests/phpunit/data/plugins/genibase-importer

# Before script, failures in this section will result in build status 'failed'
before_script:
  - npm install -g grunt-cli
  - npm install

# Script, failures in this section will result in build status 'failed'
script: grunt $GB_TRAVISCI
