# Travis CI Configuration File

env:
  global:
    - secure: "FgCl8NImpy0giLO/6nR+588kXUjcpX/TFNnFydd6Zjgjvxjk4GVAhNPSukUZgLNF6EjNPmJkzG97PV1aMtEddT7aO3sInKxORYW1FAZsz6PKnkbriYrAbop039RIPll74XQmvP+Cz2MDr5g5cNDQ8u32tVI0dlkGDzBxx8Lxy30="

sudo: false

# Tell Travis CI we're using PHP
language: php

# Build matrix options
matrix:
  include:
#    - php: 5.5
#      env: GB_TRAVISCI=travis:js
    - php: 5.4
      env: GB_TRAVISCI=travis:phpunit
    - php: 5.5
      env: GB_TRAVISCI=travis:phpunit
    - php: 5.6
      env: GB_TRAVISCI=travis:phpunit
    - php: hhvm
      env: GB_TRAVISCI=travis:phpunit
    - php: 7.0
      env: GB_TRAVISCI=travis:phpunit
    - php: 7.1
      env: GB_TRAVISCI=travis:phpunit
  allow_failures:
    - php: hhvm
    - php: 7.0
    - php: 7.1
  fast_finish: true

# Before install, failures in this section will result in build status 'errored'
before_install:
  - GB_CORE_DIR=/tmp/genibase/
  - >
    if [[ "$GB_TRAVISCI" == "travis:phpunit" ]]; then
       mysql -e "CREATE DATABASE genibase_tests;" -uroot
       cp gb-tests-config-sample.php gb-tests-config.php
       sed -i "s/youremptytestdbnamehere/genibase_tests/" gb-tests-config.php
       sed -i "s/yourusernamehere/travis/" gb-tests-config.php
       sed -i "s/yourpasswordhere//" gb-tests-config.php
    fi
#        svn checkout https://plugins.svn.wordpress.org/wordpress-importer/trunk tests/phpunit/data/plugins/genibase-importer

install:
  # Composer
  - composer self-update
  - composer install -n --prefer-source

# Before script, failures in this section will result in build status 'failed'
before_script:
  # Directories
  - mkdir .reports
  #
  - npm install -g grunt-cli
  - npm install

# Script, failures in this section will result in build status 'failed'
script:
  # Check code style (" || true" for ignoring on code style errors)
  - php vendor/bin/phpcs --report=xml --report-file=.reports/phpcs.xml || true
  # Lines of code
  - php vendor/bin/phploc --log-xml=.reports/phploc.xml src
  # Mess detection
  - php vendor/bin/phpmd ./src xml codesize,unusedcode,naming --reportfile .reports/phpmd.xml || true
  # Do tests
  - grunt $GB_TRAVISCI

after_success:
  # Generate documentation
  - bash .travis.sh

notifications:
  email: false
