# Travis CI Configuration File

sudo: false
language: php
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - COVERALLS_RUN_LOCALLY=1
    - secure: "FgCl8NImpy0giLO/6nR+588kXUjcpX/TFNnFydd6Zjgjvxjk4GVAhNPSukUZgLNF6EjNPmJkzG97PV1aMtEddT7aO3sInKxORYW1FAZsz6PKnkbriYrAbop039RIPll74XQmvP+Cz2MDr5g5cNDQ8u32tVI0dlkGDzBxx8Lxy30="
    - GH_REPO_SLUG: Limych/GeniBase
    - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
    - GH_REPO_URL: git://${TRAVIS_REPO_SLUG}
    - DOCS_PHP_VERSION: 7.1
    - GB_TRAVISCI=travis:phpunit

# Build matrix options
matrix:
  include:
#    - php: 7.1
#      env: GB_TRAVISCI=travis:js
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer self-update
  - composer install -n --prefer-source

# Before script, failures in this section will result in build status 'failed'
before_script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

# Script, failures in this section will result in build status 'failed'
script:
  - |
    if [ "$TRAVIS_PHP_VERSION" == "$DOCS_PHP_VERSION" ]; then
      phpunit --coverage-clover=build/logs/clover.xml;
    else
      phpunit;
    fi 

after_success:
  # Build Coveralls reports
  - |
    if [ "$TRAVIS_PHP_VERSION" == "$DOCS_PHP_VERSION" ]; then
      php vendor/bin/coveralls -v;
    fi
  # Generate documentation
  - |
    if [ "$TRAVIS_PHP_VERSION" == "$DOCS_PHP_VERSION" ]
    && [ "$TRAVIS_REPO_SLUG" == "$GH_REPO_SLUG" ]
    && [ $TRAVIS_BRANCH = 'master' ]
    && [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      sh docs.sh;
    fi
    
notifications:
  email: false
