# Travis CI Configuration File

sudo: false
language: php
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - secure: "FgCl8NImpy0giLO/6nR+588kXUjcpX/TFNnFydd6Zjgjvxjk4GVAhNPSukUZgLNF6EjNPmJkzG97PV1aMtEddT7aO3sInKxORYW1FAZsz6PKnkbriYrAbop039RIPll74XQmvP+Cz2MDr5g5cNDQ8u32tVI0dlkGDzBxx8Lxy30="
    - GH_REPO_SLUG: Limych/GeniBase
    - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
    - GH_REPO_URL: git://${TRAVIS_REPO_SLUG}

matrix:
  include:
    - php: 7.1
      env:
        - DOCS=yes
        - CHECKS=yes
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - mkdir -p build/logs
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - if [[ "$CHECKS" = "yes" ]]; then travis_retry composer install-devtools; fi;

before_script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

script:
  - cp ${HOME}/xdebug.ini ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - phpunit -v
  - rm ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
  - if [[ "$CHECKS" = "yes" ]]; then composer sca || return 0; fi;

after_success:
  - |
    if [[ "$DOCS" = "yes" ]]; then travis_retry php vendor/bin/coveralls -v --exclude-no-stmt; fi;
    if [[ "$DOCS" = "yes" && "$TRAVIS_REPO_SLUG" == "$GH_REPO_SLUG" && $TRAVIS_BRANCH = 'master' && $TRAVIS_PULL_REQUEST = 'false' ]]; then
      sh docs.sh
    fi
    
notifications:
  email: false
