<?php
namespace GeniBase\Tests;


use PHPUnit\Framework\TestCase;
use GeniBase\Util;

/**
 * Test class for Util.
 * Generated by PHPUnit on 2017-07-01 at 18:49:48.
 */
class UtilTest extends TestCase
{
    /**
     * @covers GeniBase\Server\Util::array_slice_keys
     */
    public function testArray_slice_keys()
    {
        $array = [
            1       => 'data',
            2       => 2,
            'key'   => 1,
            'key2'  => 'data',
        ];

        $this->assertEquals(
            [
                'key'   => 1,
            ],
            Util::array_slice_keys($array, 'key')
        );
        $this->assertEquals(
            [
                1       => 'data',
                2       => 2,
                'key2'  => 'data',
            ],
            Util::array_slice_keys($array, 1, 2, 'key2')
        );
    }

}
